version: 0.2
phases:
    install:
        commands:
            - touch .npmignore
            - sudo npm install -g gatsby
    pre_build:
        commands:
            - sudo npm install
    build:
        commands:
            - sudo npm run build
            - mkdir artifacts
            - mv public artifacts/
            - mv appspec.yml artifacts/
            - mv scripts artifacts/
artifacts:
    base-directory: artifacts
    files:
        - '**/*'
