version: 0.2
phases:
    install:
        commands:
            - touch .npmignore
            - npm install -g gatsby --unsafe-perm
    pre_build:
        commands:
            - npm install --unsafe-perm
    build:
        commands:
            - npm run build
            - mkdir artifacts
            - mv public artifacts/
            - mv appspec.yml artifacts/
            - mv scripts artifacts/
artifacts:
    base-directory: artifacts
    files:
        - '**/*'