version: 0.2
phases:
    # install:
    #     commands:
    #         - touch .npmignore
    #         - npm install --arch=x64 --platform=linux sharp
    #         - npm install -g gatsby
    # pre_build:
    #     commands:
    #         - npm install
    build:
        commands:
            - npm run build
            - mkdir artifacts
            - mv public artifacts/
            - mv appspec.yml artifacts/
            - mv scripts artifacts/
artifacts:
    base-directory: artifacts
    files:
        - '**/*'
